source 'http://rubygems.org'

gem 'rails'

gem 'sqlite3'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platform => :ruby

  gem 'uglifier'
  gem 'bootstrap-sass'
  gem 'bootstrap-datepicker-rails', :path => '../'
  gem 'jquery-rails'
end
